### ISSUE TITLE
Definição da minha paleta de cores #1

### ISSUE THREAD

**Issue by Ricardo-AFIRMA** [Ricardo-AFIRMA/RICARDO_AFIRMA#2]
segue agora codigos das cores selecionadas:
Primary color:	
#63A987  #63A987 #329464 #329464
#148B52 #148B52 #037A41 #037A41
#006836 #006836
__________________________________________________________________
Secondary color (1):	
#5B9B8F #5B9B8F #2D8876 #2D8876
#12806A #12806A #03705A #03705A
#00604D #00604D
___________________________________________________________________
Secondary color (2):	
#6EBC78 #6EBC78 #37A445 #37A445
#169B26 #169B26 #038714 #038714
#00740E #00740E
____________________________________________________________________

segue agora link para acesso as cores no paletton:
http://paletton.com/#uid=5310b0krtp5dfuslhqCvelWFpiO

**Comment by fpenha** [comment]
show.
